
#~~~~~~~~~NO Example~~~~~~~~~


#Modules allow you to encapsulate and reuse OpenTofu configurations. 
#You define a module in its own directory and then call it from your main configuration.


# modules/my-ec2-module/main.tf

variable "instance_name" {
  description = "Name tag for the EC2 instance."
  type        = string
  #since there is no default, the value MUST be provided by calling module
}

variable "instance_type" {
  description = "EC2 instance type."
  type        = string
  default     = "t2.micro"  #smallest size
}

variable "ami_id" {
  description = "AMI ID for the EC2 instance."
  type        = string
  #no default, MUST be providded by calling module
}

resource "aws_instance" "app_server" {
  #Defines actual infrastructure resource that module will create, 
  #uses input vars provided to configure the resource

  #below we are building an AWS server, its operating system, size and name
  #comes from info given when someone uses this module


  ami           = var.ami_id        #AMI is whatever val passed into module's ami_id var
  instance_type = var.instance_type #whatever passed into instanc_type again
  tags = {
    Name = var.instance_name        #Name tag set to val from instance_name var
  }
}

output "instance_id" {
  #define outputs that module with expose back to calling configuration, allows
  #calling config to use info generated by module

  #below examples function when module finishes building server, will tell whoever used it 
  #what server's unique ID is

  description = "ID of the created EC2 instance."

  value       = aws_instance.app_server.id
  #is unique ID of the app_server EC2 instance created by this module
}

